### ISSUE TITLE
About Translation license

### ISSUE THREAD

**Issue by sunny0826** [ncskier/katacoda#2]
Hi Brandon.
To help Chinese developers understand Tekton Dashboard. I fork this repository and translated this section into Chinese, but I don't see the `LICENSE` file in this repository. So I'm hoping to get your permission so that I can post a Chinese version of this section online.

Chinese version link: https://katacoda.com/guoxudong/scenarios/tekton-dashboard

**Comment by ncskier** [comment]
Hi @sunny0826, thank you so much for creating a Chinese translation of this tutorial, that's awesome! You can post the Chinese version of this tutorial 👍 

Sorry for my late response. I reached out to the Tekton team, and we would like to adopt the [Apache License that the Tekton project uses](https://github.com/tektoncd/website/blob/master/LICENSE). Eventually, I think that this tutorial will move into a repository under the tektoncd org.

**Comment by sunny0826** [comment]
Awesome! When this tutorial move into tektoncd org, I can contribution Chinese translation copy.

**Comment by anneqm** [comment]
Hi @sunny0826 .. I think we have the tutorial moved into tektoncd...  reference this pull request: https://github.com/tektoncd/website/pull/143.   If you have any questions or discussion, please reach out to the docs/website team in the tektoncd.slack.com workspace, #docs channel.   
Info on the Tekton community and joining slack is found here: https://github.com/tektoncd/community/blob/master/contact.md. Thanks!
