### ISSUE TITLE
Update to betav1

### ISSUE THREAD

**Issue by HannanSolo** [ncskier/katacoda#4]
After going through the tutorial, it seems its all based on the alpha version of tekton. Should we focus on updating this to the current version?

**Comment by ncskier** [comment]
Hi @HannanSolo 👋  thank you for raising this issue. This tutorial has been transferred over to the [tektoncd/website](https://github.com/tektoncd/website) repository (the code can be found [here](https://github.com/tektoncd/website/tree/master/tutorials/katacoda/tekton-dashboard)). So, could you please raise this issue in the [tektoncd/website](https://github.com/tektoncd/website/issues/new/choose) repository?

I just updated the [README.md](https://github.com/ncskier/katacoda) in this repo to point people to the [tektoncd/website](https://github.com/tektoncd/website) repo in the future 👍
